#!/bin/bash

readonly program="$(basename "${0}")"

function depends_on {
  local -r all_deps=("${@}")
  local missing_deps=()

  for dep in "${all_deps[@]}"; do
    command -v "${dep}" > /dev/null || missing_deps+=("${dep}")
  done

  if [[ "${#missing_deps[@]}" -gt 0 ]]; then
    echo 'Missing required tools:' >&2
    printf '  %s\n' "${missing_deps[@]}" >&2
    exit 1
  fi
}

function usage {
  echo "
    Update _shared_resources in all Workflows with 'Vítor Galvão' as the creator

    Usage:
      ${program} run

    The single argument 'run' is necessary to prevent running the script by mistake.

    Options:
      -h, --help   Show this help.
  " | sed -E 's/^ {4}//'
}

function bump_version {
  local -r old_version="${1}"
  local -r old_year="$(cut -d'.' -f1 <<< "${old_version}")"
  local -r old_release="$(cut -d'.' -f2 <<< "${old_version}")"
  local -r new_year="$(date '+%y')"

  if [[ "${old_year}" -ne "${new_year}" ]]; then
    echo -n "${new_year}.1"
  else
    echo -n "${new_year}.$(bc <<< "${old_release} + 1")"
  fi
}

if [[ "${1}" =~ ^(-h|--help)$ ]]; then
  usage
  exit 0
fi

if [[ "${1}" != 'run' ]]; then
  usage
  exit 1
fi

depends_on 'alfred-workflow-update'

echo 'Grabbing latest `_sharedresources…`'
readonly sharedresources_script="$(mktemp -d)/_sharedresources"
readonly sharedresources_url='https://raw.githubusercontent.com/vitorgalvao/alfred-workflows/master/_helpers/_sharedresources'

if [[ "$(curl --silent --head --write-out '%{http_code}' "${sharedresources_url}" --output '/dev/null')" == '200' ]]; then
  curl --silent "${sharedresources_url}" --output "${sharedresources_script}"
  chmod +x "${sharedresources_script}"
else
  echo "Could not find script at ${sharedresources_url}" >&2
  exit 1
fi

readonly sharedresources_md5="$(md5 -q "${sharedresources_script}")"

# Get Workflows directory
readonly alfred_prefs="$(ruby -r 'json' -e 'puts File.expand_path(JSON.parse(File.read(File.join(ENV["HOME"], "Library/Application Support/Alfred/prefs.json")))["current"])')"
readonly workflows_dir="${alfred_prefs}/workflows"

echo "Running in ${workflows_dir}…"

IFS=$'\n'
while read -r sharedresources_loc; do
  cd "$(dirname "${sharedresources_loc}")" || return 1

  if [[ "$(/usr/libexec/PlistBuddy -c 'print createdby' info.plist)" != 'Vítor Galvão' ]]; then
    echo 'Not at the root of one of my Workflows (does not have my name in `Created By`). Skipping…'
    continue
  fi

  workflow_name="$(/usr/libexec/PlistBuddy -c 'print name' info.plist)"
  workflow_version="$(/usr/libexec/PlistBuddy -c 'print version' info.plist)"

  new_version="$(bump_version "${workflow_version}")"

  echo -n "Updating _sharedresources in ${workflow_name}…"

  if [[ "${sharedresources_md5}" == "$(md5 -q "${sharedresources_loc}")" ]]; then
    echo ' No need to update. Skipping…'
    continue
  fi

  cp "${sharedresources_script}" "${sharedresources_loc}"

  echo ' Bumping version and commiting to repo…'
  /usr/libexec/PlistBuddy -c "set version ${new_version}" info.plist
  alfred-workflow-update 'Updated _sharedresources'
done < <(find "${workflows_dir}" -name '_sharedresources')
